#include "panview_telemetry.h"
#include "panview_uart_rx.h"
#include "panview_task_heartbeat.h"
#include "FreeRTOS.h"
#include "task.h"
#include <stdio.h>
extern volatile uint8_t panview_ui_target_present; extern volatile int16_t panview_ui_error_x_px, panview_ui_error_y_px;
void PanView_Telemetry_Collect(PanViewTelemetrySnapshot *s){ PanViewUartRxBuffer *u; PanViewStepperStatus m; PanViewSafetyStatus f; if(!s)return; u=PanView_UartRx_GetBuffer(); PanView_Stepper_GetStatus(&m); PanView_Safety_GetStatus(&f); PanView_TaskHeartbeat_CollectRuntimeInfo(); *s=(PanViewTelemetrySnapshot){0}; s->tick_ms=HAL_GetTick(); s->free_heap_bytes=xPortGetFreeHeapSize(); s->running=m.system_running; s->fault_latched=f.latched; s->fault=f.fault; s->target_present=panview_ui_target_present; s->error_x=panview_ui_error_x_px; s->error_y=panview_ui_error_y_px; s->pan_position=m.pan_position_steps; s->pitch_position=m.pitch_position_steps; s->pan_speed=m.pan_applied_speed_steps_per_second; s->pitch_speed=m.pitch_applied_speed_steps_per_second; s->pan_limit=m.pan_limit_active; s->pitch_limit=m.pitch_limit_active; s->uart_bytes=u->received_byte_count; s->uart_dropped=u->dropped_byte_count; s->uart_errors=u->error_count; s->uart_last_length=u->last_length; for(uint32_t i=0;i<PANVIEW_HEARTBEAT_COUNT;i++){const volatile PanViewHeartbeatRecord *r=PanView_TaskHeartbeat_Get((PanViewHeartbeatId)i); if(r)s->task[i]=*(const PanViewHeartbeatRecord*)r;}}
int PanView_Telemetry_Format(const PanViewTelemetrySnapshot *s,char *b,uint32_t n){if(!s||!b||n==0)return -1; return snprintf(b,n,"[SYS] t=%lu run=%u fault=%u heap=%lu\r\n[TASK] safe=%lu/%lu step=%lu/%lu vision=%lu/%lu motion=%lu/%lu\r\n[VISION] target=%u err_x=%d err_y=%d\r\n[MOTOR] pan_pos=%ld pitch_pos=%ld pan_spd=%ld pitch_spd=%ld limit=%u/%u\r\n[UART] bytes=%lu drop=%lu err=%lu last_len=%lu\r\n",(unsigned long)s->tick_ms,s->running,s->fault_latched,(unsigned long)s->free_heap_bytes,(unsigned long)s->task[PANVIEW_HEARTBEAT_SAFETY].count,(unsigned long)s->task[PANVIEW_HEARTBEAT_SAFETY].stack_high_water_mark_words,(unsigned long)s->task[PANVIEW_HEARTBEAT_STEPPER].count,(unsigned long)s->task[PANVIEW_HEARTBEAT_STEPPER].stack_high_water_mark_words,(unsigned long)s->task[PANVIEW_HEARTBEAT_VISION_RX].count,(unsigned long)s->task[PANVIEW_HEARTBEAT_VISION_RX].stack_high_water_mark_words,(unsigned long)s->task[PANVIEW_HEARTBEAT_MOTION].count,(unsigned long)s->task[PANVIEW_HEARTBEAT_MOTION].stack_high_water_mark_words,s->target_present,s->error_x,s->error_y,(long)s->pan_position,(long)s->pitch_position,(long)s->pan_speed,(long)s->pitch_speed,s->pan_limit,s->pitch_limit,(unsigned long)s->uart_bytes,(unsigned long)s->uart_dropped,(unsigned long)s->uart_errors,(unsigned long)s->uart_last_length);}
